feat: support multiple pools
teamgantt/juhwit pull request #8
Opened 2020-10-23 18:32 UTC by brianium

There are a few chores in here for process.

This will probably be a 2.0 release as it changes the API quite a bit.

Notable changes:

* Drops Laravel provider - this can be handled pretty easily in the laravel-o-sphere and it's cumbersome to test this from this repo.
* ClaimsVerifiers now verify claims as a function of a `UserPool` type. This makes it easier to conceptually separate pools and clients
* JWKs are now a requirement of the `UserPool` and need to be passed as data instead of file paths
* There is a `MultiPoolJwtDecoder` that delegates to `JwtDecoder` but allows an array of verifiers to be passed.

2020-10-23 18:38 UTC, brianium commented
@johncorrelli this PR adds pretty clean support for multiple cognito pools to juhwit. 

Sonar cloud is having a bad time with the duplication in tests. Can we turn that rule off for this repo? Or maybe ignore test directories?

Once this bad brother is merged, I'll tag it and release 2.0 so we can use it for great good 🙇

2020-10-23 18:39 UTC, brianium commented
Also, commit by commit is probably best for this feller

2020-10-26 12:59 UTC, johncorrelli commented
@brianium - sounds groovy - looking at this now. As for sonarcloud - I updated the exclusions to ignore the spec directory. Unfortunately, there is no way to re-run a test without a push, but that's fine, we can merge without that passing if need be.

2020-10-26 13:32 UTC, johncorrelli requested changes
Looks great! just a few small things. I think on the next push, it should fix the sonarcloud duplication stuff too.

2020-10-26 13:32 UTC, johncorrelli commented on composer.json
> +            "email": "brian@teamgantt.com.com"
`.com.com`

2020-10-26 13:32 UTC, johncorrelli commented on README.md
> +
if we're being picky - we don't need this extra whitespace here... but only if we're being picky.

2020-10-26 13:32 UTC, johncorrelli commented on README.md
> +$token = $decoder->decode($someTokenFromARequest);
is `$pathToJwk` above no longer needed in this example? or do we need to add more example?

2020-10-26 13:32 UTC, johncorrelli commented on spec/MultiPoolJwtDecoder.spec.php
> +                throw new InvalidClaimsException("Those claims are not invalid!");
I know this is just a test, but we have a double negative in the exception. Also, doesn't look like we're using token.

2020-10-26 13:32 UTC, johncorrelli commented on spec/MultiPoolJwtDecoder.spec.php
> +                throw new InvalidClaimsException("Those claims are not invalid! Not even a little bit!");
super not invalid. not even a lot :trollface: And `$token`

2020-10-26 13:32 UTC, johncorrelli commented on spec/MultiPoolJwtDecoder.spec.php
> +            allow($invalidClaimsVerifier)->toReceive('verify')->andRun(function ($token) {
Looks like we're not using token here, is it needed?

2020-10-26 13:45 UTC, johncorrelli approved these changes

2020-10-26 13:45 UTC, johncorrelli commented
:boom: Ready to merge! :shipit:

2020-10-26 13:46 UTC, merged